id: IDF16BA72
ocr_import_info:
  timestamp: '2023-07-21T13:40:21.899421+00:00'
  batch_id: batch-afc0
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Peche job
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-07-22 14:10:28.474727+00:00
last_modified: 2023-07-22 14:10:28.474736+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC328
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC328
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ངེས་དོན་ཕྱག་རྒྱ་ཆེན་པོའི་སྒོམ་རིམ་གསལ་བར་བྱེད་པའི་ལེགས་བཤད་ཟླ་བའི་འོད་ཟེར།
  languages:
  - bo
  author: དྭགས་པོ་པཎ་ཆེན་བཀྲ་ཤིས་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.9968386911801828
  ocr_word_median_confidence_index: 1.0
bases:
  I2PD18824:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18824
      total_pages: 338
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD18824.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9968386911801828
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
